name: example-environment
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9 # for pyproj
  - numpy
  - scipy
  - xarray=0.18.2 # see https://github.com/ajdawson/eofs/issues/123
  - matplotlib
  - cartopy
  - eofs
  - hvplot=0.7.3 
  - geoviews
  - pyproj
