name: example-environment
channels:
  - conda-forge
  - defaults
dependencies:
  - python
  - numpy
  - scipy
  - xarray
  - matplotlib
  - cartopy
  - eofs
  #- hvplot
  - geoviews
  - pyproj
#  - pip
#  - pip:
#    - notebook-as-pdf==0.5.0
