name: example-environment
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - numpy
  - scipy
  #- xarray
  - xarray=2024.10.0  # 2023.12.0
  - matplotlib
  - cartopy
  #- xeofs
  - eofs
  - hvplot
  #- pooch
  #- geoviews
  #- pyproj
#  - pip
#  - pip:
#    - notebook-as-pdf==0.5.0
